
package businesslogic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankTransactionsService", targetNamespace = "http://businesslogic/", wsdlLocation = "http://localhost:8082/dlte?wsdl")
public class BankTransactionsService
    extends Service
{

    private final static URL BANKTRANSACTIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKTRANSACTIONSSERVICE_EXCEPTION;
    private final static QName BANKTRANSACTIONSSERVICE_QNAME = new QName("http://businesslogic/", "BankTransactionsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/dlte?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKTRANSACTIONSSERVICE_WSDL_LOCATION = url;
        BANKTRANSACTIONSSERVICE_EXCEPTION = e;
    }

    public BankTransactionsService() {
        super(__getWsdlLocation(), BANKTRANSACTIONSSERVICE_QNAME);
    }

    public BankTransactionsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKTRANSACTIONSSERVICE_QNAME, features);
    }

    public BankTransactionsService(URL wsdlLocation) {
        super(wsdlLocation, BANKTRANSACTIONSSERVICE_QNAME);
    }

    public BankTransactionsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKTRANSACTIONSSERVICE_QNAME, features);
    }

    public BankTransactionsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankTransactionsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankTransactions
     */
    @WebEndpoint(name = "BankTransactionsPort")
    public businesslogic.BankTransactions getBankTransactionsPort() {
        return super.getPort(new QName("http://businesslogic/", "BankTransactionsPort"), businesslogic.BankTransactions.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankTransactions
     */
    @WebEndpoint(name = "BankTransactionsPort")
    public businesslogic.BankTransactions getBankTransactionsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://businesslogic/", "BankTransactionsPort"), businesslogic.BankTransactions.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKTRANSACTIONSSERVICE_EXCEPTION!= null) {
            throw BANKTRANSACTIONSSERVICE_EXCEPTION;
        }
        return BANKTRANSACTIONSSERVICE_WSDL_LOCATION;
    }

}
