//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.03 at 12:53:41 PM IST 
//


package dltespringsoapwebservice.web.dlte.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dltespringsoapwebservice.web.dlte.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dltespringsoapwebservice.web.dlte.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetByIdResponse }
     * 
     */
    public GetByIdResponse createGetByIdResponse() {
        return new GetByIdResponse();
    }

    /**
     * Create an instance of {@link Officials }
     * 
     */
    public Officials createOfficials() {
        return new Officials();
    }

    /**
     * Create an instance of {@link ListOfficialResponse }
     * 
     */
    public ListOfficialResponse createListOfficialResponse() {
        return new ListOfficialResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link NewOfficialResponse }
     * 
     */
    public NewOfficialResponse createNewOfficialResponse() {
        return new NewOfficialResponse();
    }

    /**
     * Create an instance of {@link NewOfficialRequest }
     * 
     */
    public NewOfficialRequest createNewOfficialRequest() {
        return new NewOfficialRequest();
    }

    /**
     * Create an instance of {@link DeleteViaIdResponse }
     * 
     */
    public DeleteViaIdResponse createDeleteViaIdResponse() {
        return new DeleteViaIdResponse();
    }

    /**
     * Create an instance of {@link DeleteViaIdRequest }
     * 
     */
    public DeleteViaIdRequest createDeleteViaIdRequest() {
        return new DeleteViaIdRequest();
    }

    /**
     * Create an instance of {@link GetByIdRequest }
     * 
     */
    public GetByIdRequest createGetByIdRequest() {
        return new GetByIdRequest();
    }

    /**
     * Create an instance of {@link ListOfficialRequest }
     * 
     */
    public ListOfficialRequest createListOfficialRequest() {
        return new ListOfficialRequest();
    }

}
