
package host;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KycCRUDL", targetNamespace = "http://host/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    host.ObjectFactory.class
})
public interface KycCRUDL {


    /**
     * 
     * @return
     *     returns host.ListOfKYC
     */
    @WebMethod
    @WebResult(name = "ListOfKYC", partName = "ListOfKYC")
    @Action(input = "http://host/KycCRUDL/fetchRequest", output = "http://host/KycCRUDL/fetchResponse")
    public host.ListOfKYC fetch();

    /**
     * 
     * @param kyc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", partName = "ResponseMessage")
    @Action(input = "http://host/KycCRUDL/addKycRequest", output = "http://host/KycCRUDL/addKycResponse")
    public String addKyc(
        @WebParam(name = "KYC", partName = "KYC")
        host.Kyc kyc);

}
